final List<String> fieldRulesDemo = [
  "對技術有較高要求",
  "不適合快樂玩/撲碟人士",
  "要懂高遠球，殺球，接殺球，網前及雙打走位的攻防意識(進攻前後企，防守左右企)",
  "男女不拘，懂雙打計分",
  "若不能出席，請在開場前48小時前通知。若開場前48小時內通知， 場費要照付",
  "dmspvmpdsvm amicopcmp osam opcmasop maspm opascm pasmc pamscop amsopmoapsc mopascomp",
  "dfsiopfainbon oasnbo ainbo fodn b",
  "osavn ovn iaonvo",
  "amnoibvm ovmo as",
  "mvaom maiov ma",
  "dmspvmpdsvm amicopcmp osam opcmasop maspm opascm pasmc pamscop amsopmoapsc mopascomp",
  "dfsiopfainbon oasnbo ainbo fodn b",
  "osavn ovn iaonvo",
  "amnoibvm ovmo as",
  "mvaom maiov ma",
  "dmspvmpdsvm amicopcmp osam opcmasop maspm opascm pasmc pamscop amsopmoapsc mopascomp",
  "dfsiopfainbon oasnbo ainbo fodn b",
  "osavn ovn iaonvo",
  "amnoibvm ovmo as",
  "mvaom maiov ma",
  "dmspvmpdsvm amicopcmp osam opcmasop maspm opascm pasmc pamscop amsopmoapsc mopascomp",
  "dfsiopfainbon oasnbo ainbo fodn b",
  "osavn ovn iaonvo",
  "amnoibvm ovmo as",
  "mvaom maiov ma",
];
